apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-app
spec:
  replicas: 1
  selector:
    matchLabels: # label here tells us that all pods that have this label belong to this Deployment
      app: pokedex
  template: # configuration for pod
    metadata:
      labels: # all pods replica will have the same label
        app: pokedex
    spec:
      containers:
      - name: pokedex-app
        image: pokedex-app:v1
        ports:
        - containerPort: 30000
        imagePullPolicy: Never # we have to set this to "Never" otherwise k8s will keep pulling image from network instead of local
---
apiVersion: v1
kind: Service
metadata:
  name: pokedex-service
spec:
  type: NodePort
  selector:
   app: pokedex
  ports:
    - port: 30000 # service port
      protocol: TCP
      targetPort: 30000 # containerPort of Deployment
      nodePort: 30200